const cities = [
    "Jakarta",
    "Surabaya",
    "Medan",
    "Bandung",
    "Bekasi",
    "Palembang",
    "Tangerang",
    "Makassar",
    "Semarang",
    "Depok",
    "Padang",
    "Bandar Lampung",
    "Bogor",
    "Malang",
    "Yogyakarta",
    "Pekanbaru",
    "Serang",
    "Surakarta",
    "Cimahi",
    "Pontianak",
    "Banjarmasin",
    "Balikpapan",
    "Jambi",
    "Mataram",
    "Manado",
    "Cilegon",
    "Kupang",
    "Palangkaraya",
    "Tegal",
    "Binjai",
    "Banda Aceh",
    "Denpasar",
    "Batam",
    "Jayapura",
    "Semarang",
    "Bengkulu",
    "Gorontalo",
    "Jambi",
    "Kendari",
    "Kotamobagu",
    "Samarinda",
    "Tanjung Selor",
]